repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: ''
    hooks:
    -   id: autopep8