deploy:
  provider: heroku
  api_key:
    secure: "75c98af0-22a3-47d7-98dc-a5ec0169350f"

matrix:
    include:
        - language: python
          cache: pip
          python: "3.8.1"
          install:
            - pip install pipenv --upgrade
            - pipenv sync -d
          before_script:
            - python --version
          script:
            - flake8
            - pytest
            - coverage erase
            - coverage run -m pytest && coverage html
          after_success:
            - bash <(curl -s https://codecov.io/bash)
            - deploy